---Querys de tabelas criadas para ver as predições geradas em um dia específico, como foco nos alunos com risco real de evasão (nível ALTO)



SELECT * FROM ML_evasao_PRESENCIAL A
INNER JOIN ML_PREDICAO_PRESENCIAL B ON A.ALUNO = B.ALUNO
WHERE  A.QTD_PERIODOS > 1
AND B.DATA_DE_INSERCAO = '2025-07-28'
and B.PROB_EVASAO < 0.75 and B.PROB_EVASAO >= 0.5
AND A.PERFIL_RISCO NOT IN ('EST�VEL')

SELECT * FROM ML_EVASAO_EAD A
INNER JOIN ML_PREDICAO_EAD B ON A.ALUNO = B.ALUNO
WHERE  A.QTD_PERIODOS > 1
AND B.DATA_DE_INSERCAO = '2025-07-28'
and B.PROB_EVASAO < 0.75 and B.PROB_EVASAO >= 0.5
AND A.PERFIL_RISCO NOT IN ('EST�VEL')

SELECT * FROM ML_EVASAO_HIBRIDO A
INNER JOIN ML_PREDICAO_HIBRIDO B ON A.ALUNO = B.ALUNO
WHERE  A.QTD_PERIODOS > 1
AND B.DATA_DE_INSERCAO = '2025-07-28'
and B.PROB_EVASAO < 0.75 and B.PROB_EVASAO >= 0.5
AND A.PERFIL_RISCO NOT IN ('EST�VEL')

